### ISSUE TITLE
Could you provide the public code as soon as possible, please

### ISSUE THREAD

**Issue by SUTwu** [LI-Hao-SJTU/DerainRLNet#1]
Hello, I'm a student. I'm currently studying rain removal. Can you provide the public code as soon as possible? Thank you very much.

**Comment by LI-Hao-SJTU** [comment]
Hello, thanks for reminding. The code is uploaded.

----- 原始邮件 -----
发件人: "Groot2020665" ***@***.***>
收件人: "LI-Hao-SJTU/DerainRLNet" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期四, 2021年 10 月 07日 上午 10:34:17
主题: [LI-Hao-SJTU/DerainRLNet] Could you provide the public code as soon as possible, please (#1)

Hello, I'm a student. I'm currently studying rain removal. Can you provide the public code as soon as possible? Thank you very much.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/LI-Hao-SJTU/DerainRLNet/issues/1
